checkoutLocation: gitpod

github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: true
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to true)
    addComment: true
    # add a "Review in Gitpod" button to pull requests (defaults to false)
    addBadge: false
    # add a label once the prebuild is ready to pull requests (defaults to false)
    addLabel: prebuilt-in-gitpod

tasks:
  - before: curl -s https://get.nextflow.io | bash && mv nextflow /home/gitpod/.rvm/bin/ && exit

  - name: Open README.md preview
    command: code README.md
  - name: Open shell
    command: clear && bash

vscode:
  extensions: # based on nf-core.nf-core-extensionpack
    - codezombiech.gitignore # Language support for .gitignore files
    - esbenp.prettier-vscode # Markdown/CommonMark linting and style checking for Visual Studio Code
    - nextflow.nextflow                    # Nextflow syntax highlighting
    - streetsidesoftware.code-spell-checker # Spelling checker for source code
    - ms-vscode.live-server
    - matt-rudge.auto-open-preview-panel